name: flutter_map_line_editor
description: Line editor class for flutter_map
version: 3.0.0
repository: https://github.com/ibrierley/flutter_map_line_editor

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^2.0.0
  flutter_map_dragmarker:
    git:
      url: https://github.com/eidolonFIRE/flutter_map_dragmarker.git
  latlong2: ^0.8.0

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter
